- .gitignore
- README.md
- docker-compose.yml
- etc/csp_whitelist.xml
Add docker and docker compose with a volume pointing to localhost
> Add docker and docker compose

- Controller/Adminhtml/Log/Save.php
- Helpers/Log.php
- Helpers/OrderHelper.php
- Model/Request/Transactions.php
- Observer/CreateOrder.php
- Ui/Component/OrderIdButton.php
- composer.json
- view/adminhtml/ui_component/log_listing_mondu.xml
- view/frontend/web/js/view/payment/method-renderer/mondu.js
Street number missing fix
Tax must be integer fix
Cart discount bugfix
> Shirtracer fixes.

- Controller/Webhooks/Index.php
- Model/Ui/ConfigProvider.php
- Observer/Config/Save.php
- composer.json
- etc/adminhtml/system.xml
- etc/config.xml
- etc/module.xml
fixes [BNPL-2534](https://mondu.atlassian.net/browse/BNPL-2534)
> option to select new order state in config, order status consistency fix

- .github/workflows/release.yml
Release: p
Tickets: BNPL-2508
Description: Added auto release CI, packagist auto update trigger
> Added auto release updating ci

- .github/workflows/release.yml
Release: p
Tickets: BNPL-2508
Description: packagist auto update trigger removed from post script
[BNPL-2508]: https://mondu.atlassian.net/browse/BNPL-2508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feature-BNPL-2508]: [Magento 2] CI/CD

- .github/workflows/release.yml
Release: p
Tickets: BNPL-2508
Description: added force push on github workflow changes
> [feature-BNPL-2508]: [Magento 2] CI/C

- Helpers/Log.php
- Setup/UpgradeSchema.php
> BNPL-2619 Save authorized net terms

- Helpers/DataPlugin.php
- Helpers/PaymentMethod.php
- Model/PaymentMethodList.php
- Model/Request/CommonRequest.php
- Observer/Config/Save.php
- composer.json
- etc/module.xml
Release: p
Tickets: CON-767, CON-185
Description: Added cache on error for payment methods request.
> Authorization issue and 100 status code

- view/adminhtml/web/style.css
- view/frontend/web/css/mondu.css
Changes logos to hosted urls
Release: -
Tickets: [CON-801](https://mondu.atlassian.net/browse/CON-801)
[CON-801]: https://mondu.atlassian.net/browse/CON-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> change to hosted logo

- Model/Ui/ConfigProvider.php
- etc/adminhtml/system.xml
Minor bugfix for payment method title configuration in store view
Release: -
Tickets: CON-819
> read payment method titles from store view config

- Helpers/InvoiceOrderHelper.php
Fixes no invoices being saved locally in case option "require invoice for shipment" is turned off
Release:
Tickets: CON-828
> store invoices in database for no invoice for shipment option

- composer.json
- etc/module.xml
- view/frontend/web/js/view/payment/method-renderer/mondu.js
Bugfix for merchant
Please **specify** p/m/M/- for patch/minor/major/none
Release: p
Please **specify** only ticket id's separated with commas (F.E. BNPL-21, BNPL-22)
Tickets: Con-815
> Baushop express magento 2 sporadic error during checkout with installments

- Observer/CreateOrder.php
Removes unwanted functionality.
Release: -
Tickets: CON-859
> removed overwriting billing/shipping data based on mondu order

- composer.json
- etc/module.xml
This release removes unwanted functionality that overwrites shipping/billing address for the buyer when creating the order.
Release: p
Tickets: CON-859
> 1.1.15 version bump

- Helpers/BulkActions.php
- Helpers/InvoiceOrderHelper.php
- Helpers/Log.php
- Helpers/MonduTransactionItem.php
- Helpers/OrderHelper.php
- Model/MonduTransactionItem.php
- Model/Request/CommonRequest.php
- Model/ResourceModel/MonduTransactionItem.php
- Model/ResourceModel/MonduTransactionItem/Collection.php
- Observer/CreateOrder.php
- Observer/UpdateOrder.php
- Setup/UpgradeSchema.php
- composer.json
- etc/module.xml
Change external reference id used from variationID to variationID-quoteitemID
Fixes # [(CON-922)](https://mondu.atlassian.net/browse/CON-922?atlOrigin=eyJpIjoiNjQ5YWE4MTkxOWJjNGVjZjk4MWUzMTE2OWNiNGM3ZmIiLCJwIjoiaiJ9)
Release: p
Tickets: CON-922
> External reference id change.

- Observer/UpdateOrder.php
If an api error occurs during credit note creation we will only show an error message but allow the merchant to create them in his system.
Please **specify** p/m/M/- for patch/minor/major/none
Release: -
Please **specify** only ticket id's separated with commas (F.E. BNPL-21, BNPL-22)
Tickets:
> Show error message instead of throwing an error on certain api errors during credit note creation.

- Helpers/AdditionalCosts/AdditionalCosts.php
- Helpers/AdditionalCosts/AdditionalCostsInterface.php
- Helpers/OrderHelper.php
- etc/di.xml
Adds AdditionalCostsInterface interface that can be mapped to a custom implementation by the merchant.
Release: -
Tickets:
> Allows merchants to include buyer fee cents 

- Helpers/AdditionalCosts/AdditionalCosts.php
- composer.json
- etc/module.xml
Fixes PHP 8.1 deprecation issue.
Release: p
Tickets: -
> Hotfix deprecation PHP 8.1

- Model/Request/Transactions.php
Add buyer external_reference_id
Release: -
Tickets:
> Added external_reference_id for buyers.

- Controller/Webhooks/Index.php
- composer.json
- etc/module.xml
Use $order->getData() instead of $order->getData
Release: p
Tickets: -
> Hotfix Webhooks

- Controller/Webhooks/Index.php
Fixed logical error in webhooks
Release: -
Tickets: CON-1173
> Fixed logical error in webhooks.

- Controller/Payment/Checkout/AbstractPaymentController.php
- Controller/Payment/Checkout/Cancel.php
- Controller/Payment/Checkout/Decline.php
- Controller/Payment/Checkout/Success.php
- composer.json
- etc/module.xml
Hotfix for invalid return types in Controllers
Release: p
Tickets:-
> hotfix invalid return type

- Model/Request/Transactions.php
- composer.json
- etc/module.xml
Hotfix buyer external reference
> Hotfix buyer external reference

- Helpers/BuyerParams/BuyerParams.php
- Helpers/BuyerParams/BuyerParamsInterface.php
- Model/Request/Transactions.php
- Model/Ui/ConfigProvider.php
- composer.json
- etc/di.xml
- etc/module.xml
Allow merchants to overwrite buyer params.
Release: p
Tickets: PT-148
> Allow merchant to modify buyer params

- composer.json
- etc/module.xml
- view/frontend/web/js/view/payment/method-renderer/mondu.js
Fix address duplicate
Fixes [PT-319](https://mondu.atlassian.net/browse/PT-319)
Release: p
Tickets: PT-319
[PT-319]: https://mondu.atlassian.net/browse/PT-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix-PT-319]: Fix address duplicate

- Helpers/BulkActions.php
- Model/Ui/ConfigProvider.php
- Setup/Patch/Data/CronJobPatch.php
- composer.json
- etc/adminhtml/system.xml
- etc/crontab.xml
Extended system.xml to accept new configuration value for order status ( cron job will check if the order is in that status before creating an invoice for it )
Release: p
Tickets: PT-967
> [PT-967] Improve cron job functionality

- Plugin/ProcessShipmentSave.php
- etc/di.xml
Add a plugin to handle the case when the Magento REST API creates the shipment for the invoice.
https://mondu.atlassian.net/browse/PT-1020
Release: p
Tickets: [PT-967](https://mondu.atlassian.net/browse/PT-1020)
[PT-967]: https://mondu.atlassian.net/browse/PT-967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PT-1020] Invoice Generation from API is not working

- composer.json
- etc/adminhtml/system.xml
- etc/module.xml
Added sort order configuration for 4 Mondu payment methods
Release: p
Tickets: PT-1438
> [PT-1438] Added sort order to plugin configuration

- Helpers/Log.php
- Plugin/AddTemplateVariable.php
- composer.json
- etc/module.xml
Fixing the error in CreateOrder observer.
Release: p
Tickets: PT-1774
[Fixes # (issue)](https://mondu.atlassian.net/browse/PT-1774)
> PT-1774: Magento2-Shirtracer-LIVE - Error in CreateOrder observer.

- composer.json
- etc/module.xml
- i18n/bg_BG.csv
- i18n/cs_CZ.csv
- i18n/el_GR.csv
- i18n/es_ES.csv
- i18n/it_IT.csv
- i18n/pl_PL.csv
- i18n/pt_PT.csv
- i18n/ro_RO.csv
- view/adminhtml/ui_component/log_listing_mondu.xml
Added translations for many languages.
Release: p
Tickets: PT-1878
> PT-1878 Added many translations

- Controller/Adminhtml/Log/Save.php
- Controller/Payment/Checkout/Token.php
- Controller/Webhooks/Index.php
- Helpers/OrderHelper.php
- Helpers/PaymentMethod.php
- Model/Request/Transactions.php
- Observer/CreateOrder.php
- composer.json
- etc/csp_whitelist.xml
- etc/module.xml
Fixing the CSP error issue
Release: p
Tickets: PT-2738
[Fixes # (issue)](https://mondu.atlassian.net/browse/PT-2738)
> PT-2738: Magento: Support Hyvä theme.
